In [1]:
import numpy as np
arr=np.array([1,3,4,5])
print(arr)

[1 3 4 5]


# Zeros Array

In [15]:
z=np.zeros((3,3,4))
print(z)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [18]:
ran=np.random.random((2,3))
print(ran)

[[0.80323988 0.60648462 0.0483663 ]
 [0.43345652 0.34055347 0.48556131]]


# Same Number Full Function

In [23]:
fl=np.full((2,3),3)
print(fl)

[[3 3 3]
 [3 3 3]]


# Arranging the value

In [27]:
a=np.arange(3,20,3)
print(a)

[ 3  6  9 12 15 18]


# Linespace Intervel between

In [32]:
l=np.linspace(1,5,5)
print(l)

[1. 2. 3. 4. 5.]


In [37]:
a=np.array([[2,3,4],[3,5,6]])
print(a.shape)
print(a.size)
print(a.ndim)

(2, 3)
6
2


# Arange and res

In [51]:
a=np.arange(24,dtype=float)
print(a.size)
print(a.dtype)
b=a.reshape(3,4,2)
print(b)


24
float64
[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]
  [ 6.  7.]]

 [[ 8.  9.]
  [10. 11.]
  [12. 13.]
  [14. 15.]]

 [[16. 17.]
  [18. 19.]
  [20. 21.]
  [22. 23.]]]


In [52]:
a=np.sum([20,30])
print(a)

50


In [61]:
s=np.sum([[0,2],[2,3]],axis=0)
print(s)

[2 5]


In [71]:
a=[1,2,3]
c=[3,4,5]
b=[1,2,3]
s=np.equal(a,c)
print(s)
s1=np.array_equal(a,b)
print(s1)

[False False False]
True


In [81]:
on=np.ones([3,4])
print(on)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [97]:
a=np.array([[[2,3],[2,4],[3,6]]])
print("befor reshap\n",a)
print(a.size)
print(a.shape)
print(a.ndim)
print(a.reshape(2,3))

befor reshap
 [[[2 3]
  [2 4]
  [3 6]]]
6
(1, 3, 2)
3
[[2 3 2]
 [4 3 6]]


# Digonal method

In [102]:
d=np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [106]:
l=[2,3,4,5]
d1=np.diag(l)
print(d1)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


# indexing and slicing

In [116]:
arr=np.array([2,3,4,5,6])
print(arr[0])
print(arr[-1])
print(arr[[0,-1]])

2
6
[2 6]


# multy array

In [132]:
arr2=np.array([[[2,3,4],[3,5,7],[5,79,8]]])
print(arr2)
print(arr2[0,0])
print(arr2[0,1])
print(arr2[0,2])
print(arr2[:-1])
print(arr2.ndim)

[[[ 2  3  4]
  [ 3  5  7]
  [ 5 79  8]]]
[2 3 4]
[3 5 7]
[ 5 79  8]
[]
3
